In [3]:
import numpy as np

a = np.array(['t', 'b', 'r', 'd', 'e', 'f', 'z', 'a'])
b = np.random.randint(1, 20, 8)

print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[ 1  2 14  7 17 14  5  6]


In [4]:
print(b > 10)

[False False  True False  True  True False False]


In [6]:
bool_arr = b > 10
print(bool_arr)
new_arr = b[bool_arr]
print(new_arr)

[False False  True False  True  True False False]
[14 17 14]


In [7]:
new_arr = b[b>10]
new_arr

array([14, 17, 14])

In [12]:
new_arr = b[(b<10) & (b>5)]
new_arr

array([7, 6])

In [21]:
print(b)
c = b
c

[ 1  2 14  7 17 14  5  6]


array([ 1,  2, 14,  7, 17, 14,  5,  6])

In [22]:
c[:3] = 19
c

array([19, 19, 19,  7, 17, 14,  5,  6])

In [23]:
c[c > 15] = 100
c

array([100, 100, 100,   7, 100,  14,   5,   6])

In [29]:
ind_arr = np.where(c == 100)
print(ind_arr)
print(a[ind_arr]) # → This is equivalent to:

## if b[i] == 100:
##    print(a[i])

(array([0, 1, 2, 4]),)
['t' 'b' 'r' 'e']
