In [8]:
import numpy as np

a = np.random.randint(1, 30, (5, 6))
print(a)

[[29 13  7 14 12 22]
 [11 14 11 21 13 27]
 [ 4  9 18  6 24  9]
 [ 1 13 13  4 27 24]
 [25 23 23 27 26 16]]


In [9]:
bool_arr = a > 20
print(bool_arr)

[[ True False False False False  True]
 [False False False  True False  True]
 [False False False False  True False]
 [False False False False  True  True]
 [ True  True  True  True  True False]]


In [10]:
c = a[bool_arr]
c

array([29, 22, 21, 27, 24, 27, 24, 25, 23, 23, 27, 26])

In [11]:
a[bool_arr] = 100
a

array([[100,  13,   7,  14,  12, 100],
       [ 11,  14,  11, 100,  13, 100],
       [  4,   9,  18,   6, 100,   9],
       [  1,  13,  13,   4, 100, 100],
       [100, 100, 100, 100, 100,  16]])

In [13]:
d = np.random.randint(1, 10, (2,2))
d

array([[6, 3],
       [8, 3]])

In [14]:
d_bool = np.array([[True, False], [False, True], [True, True]])
d_bool

array([[ True, False],
       [False,  True],
       [ True,  True]])

In [16]:
print(d[d_bool])

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 3

In [18]:
# Error becoz :  d → 2 x 2
#           d_bool → 3 x 2

In [19]:
boolean_arr = a[:, 3] == 100
print(boolean_arr)

[False  True False False  True]


In [21]:
a[boolean_arr, 3] = 99
a

array([[100,  13,   7,  14,  12, 100],
       [ 99,  99,  99,  99,  99,  99],
       [  4,   9,  18,   6, 100,   9],
       [  1,  13,  13,   4, 100, 100],
       [ 99,  99,  99,  99,  99,  99]])