###### 1. np.array(first_arg {Array-like Object}, dtype)

In [4]:
import numpy as np

a = [1,2,3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
a = [1,2,3,'5','a',4.5]
b = np.array(a)
print(b)

# See output: Every element in the array is a string

['1' '2' '3' '5' 'a' '4.5']


##### Unlike lists numpy arrays can not store elements of different types, hence it has converted every element to array
##### We can overcome this by using 2nd parameter which is "dtype"

In [8]:
a = [1,2,3,'5','a',4.5]
b = np.array(a, dtype= int)
print(b)

ValueError: invalid literal for int() with base 10: 'a'

In [9]:
a = [1,2,3,'5',4.5]
b = np.array(a, dtype= int)
print(b)

[1 2 3 5 4]


In [10]:
a = [1,2,3,'5',4.5]
b = np.array(a*3)
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


In [12]:
b = np.ones(3)
b

array([1., 1., 1.])

In [20]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [21]:
b = np.ones((2,3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [15]:
b = np.zeros(3, dtype = int)
b

array([0, 0, 0])

In [22]:
b = np.zeros((4,3), dtype = int)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
b = np.full((4,2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2],
       [2, 2]])

In [50]:
b = np.empty((4,4), dtype=int)
b

array([[ 0, 19,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

###### Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]] , create a numpy 2D array using it.

In [55]:
import numpy as np
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###### Create an integer array of size 10, where all the values should be O but the fifth value should be 1.

In [59]:
import numpy as np
a = np.zeros(10, dtype = int)
a[5]
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])