##### np.arange()

In [2]:
import numpy as np
a = np.arange(2, 10, 2)
a

array([2, 4, 6, 8])

In [3]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### np.linspace()

In [5]:
import numpy as np
b = np.linspace(2, 10)
# b

## we can't set a step value in this method
print(b[2] - b[1])
print(b[3] - b[2])
print(b[1] - b[0]) # step value

0.16326530612244872
0.16326530612244916
0.16326530612244916


In [10]:
a = np.linspace(2, 10, 5, dtype=int)
a

array([ 2,  4,  6,  8, 10])

In [12]:
a = np.linspace(2, 10, 5, dtype=int, endpoint = False)
a

array([2, 3, 5, 6, 8])

In [14]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
b = np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [24]:
b = np.random.rand(3)
b

array([0.73676145, 0.72967115, 0.99939901])

In [25]:
b = np.random.rand(2,3)
bx

array([[0.93030594, 0.71233907, 0.48175675],
       [0.06812026, 0.64559794, 0.28920585]])

In [11]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [12]:
np.random.rand()

0.6073305863695078

In [15]:
b = np.random.randint(10, size = (4,4))
b

array([[4, 7, 4, 5],
       [3, 7, 7, 2],
       [2, 2, 8, 2],
       [9, 0, 3, 5]])