###### NumPy arrays are basically a collection of references or pointers which point to:
- data → reference to 1st byte of the array / 1st element of the array
- dtype → data type
- shape → size of the array
- strides → number of bytes to be skipped to get to the next element

### 1-D Array

In [5]:
import numpy as np

li = [1,2,3,4,5]
arr = np.array(li)

print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [8]:
print(arr.data)
print(arr.shape)
print(arr.strides)
print(arr.dtype)

(5,)
(8,)
int64


###### Accessing elements of the NumPy array

In [15]:
print(li[2])
print(arr[2])
print(li[1:4])
print(arr[1:4])

3
3
[2, 3, 4]
[2 3 4]


### 2-D Array

In [4]:
import numpy as np

li_2d = [[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]]
arr_2d = np.array(li_2d)

print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [7]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.strides)
print(arr_2d.dtype)

(4, 4)
(32, 8)
int64


###### Accessing elements of the NumPy array

In [20]:
print(li_2d[2][3])
print(arr_2d[2][3])
# print(li_2d[2,3])  → Not allowed
print(arr_2d[2,3])

12
12
12


In [31]:
print(li_2d[2][1:3])
print(arr_2d[2,1:3])

[10, 11]
[10 11]


In [32]:
print(li_2d[0:3][2])

[9, 10, 11, 12]


In [34]:
## Let's see how did this happen!

x = li_2d[0:3]
print(x)
y = x[2]
print(y)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]


In [38]:
print(arr_2d[0:3,1])

[ 2  6 10]


In [40]:
print(li_2d[0:3][3])

### it will show erro bcoz
### li_2d[0:3] → [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

IndexError: list index out of range

In [42]:
print(arr_2d[2:4, 1:3])
# can't do this using normal 2d list

[[10 11]
 [14 15]]
