## Mathematical Operations

In [10]:
import numpy as np
li = [1,2,3,4,5]
a = np.random.randint(1, 20, 5)
b = np.random.randint(1, 20, 5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 7  5  2  1 16]
[14 13  7 16  6]


#### Increase each element in the list and both the numpy arrays

In [23]:
# In list

li = [i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [28]:
# In nupmy arrays

a += 1
a

array([ 8,  6,  3,  2, 17])

In [29]:
b += 1
b

array([15, 14,  8, 17,  7])

In [31]:
c = a+b
c

array([23, 20, 11, 19, 24])

In [32]:
d = a - b
d

array([ -7,  -8,  -5, -15,  10])

In [34]:
e = a*b
e

array([120,  84,  24,  34, 119])

In [35]:
f = a/b
f

array([0.53333333, 0.42857143, 0.375     , 0.11764706, 2.42857143])

In [36]:
g = a//b
g

array([0, 0, 0, 0, 2])

In [37]:
h = a**b
h

array([35184372088832,    78364164096,           6561,         131072,
            410338673])

In [43]:
print(a.sum())
print(a.mean())
print(a.min())
print(a.max())
print(a.argmin()) # returns the index of the min element
print(a.argmax())

36
7.2
2
17
3
4


## Relational and Logical Operations

In [44]:
print(a)
print(b)

[ 8  6  3  2 17]
[15 14  8 17  7]


In [45]:
a > b

array([False, False, False, False,  True])

In [46]:
a < b

array([ True,  True,  True,  True, False])

In [47]:
a == b

array([False, False, False, False, False])

In [48]:
print(np.logical_or(a, b))
print(np.logical_and(a, b))

[ True  True  True  True  True]
[ True  True  True  True  True]


In [50]:
a[2] = 0
print(np.logical_not(a))

[False False  True False False]
