### Compatibility Rules:
1. Equal sizes
2. One of them is 1

Examples:

- ✅ X → [2,3] ; Y → [2,3]
- ❌ X → [2,1] ; Y → [2,3]
- ✅ X → [3,3] ; Y → [3] basically means (1, 3)

In [3]:
import numpy as np

x = np.random.randint(1, 10, (3,3))
y = np.random.randint(1, 10, (3,3))

print(x)
print()
print(y)

[[5 1 8]
 [2 8 3]
 [7 3 1]]

[[8 7 5]
 [3 2 7]
 [8 8 1]]


In [4]:
ans = x - y
print(ans)

[[-3 -6  3]
 [-1  6 -4]
 [-1 -5  0]]


In [9]:
import numpy as np

x = np.random.randint(1, 10, (3,3))
y = np.random.randint(1, 10, (3))

print(x)
print()
print(y)

[[1 8 6]
 [9 5 8]
 [1 5 9]]

[4 8 6]


In [10]:
ans = x - y
print(ans)

[[-3  0  0]
 [ 5 -3  2]
 [-3 -3  3]]


In [17]:
import numpy as np

x = np.random.randint(1, 10, (3,2))
y = np.random.randint(1, 10, (2,3))

print(x)
print()
print(y)

[[2 8]
 [5 8]
 [2 1]]

[[6 3 7]
 [6 2 2]]


In [12]:
ans = x - y
print(ans)

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [ ]:
## How can we overcome this?

In [13]:
# 1. Transpose

In [18]:
y = np.transpose(y)
y

array([[6, 6],
       [3, 2],
       [7, 2]])

In [19]:
ans = x - y
print(ans)

[[-4  2]
 [ 2  6]
 [-5 -1]]
